### ISSUE TITLE
Tests Don't Pass on Tensorflow 0.11rc0

### ISSUE THREAD

**Issue by xanderdunn** [yaroslavvb/imperative#1]
Testing with Python2 tensorflow 0.10.0 runs successfully.  

With 0.11.0rc0, I get errors:
`tests/run_all_tests.sh`:

```
Running simple test
Running env_test.py
.E...........E.EE.EE.....
======================================================================
ERROR: testConcat (__main__.EnvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "tests/env_test.py", line 165, in testConcat
    self.assertEqual(env.tf.concat(0, 5), 5)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 867, in concat
    dtype=dtypes.int32).get_shape(
  File "/local/dev/imperative/imperative/__amalgam__.py", line 142, in get_shape
    shape_tensor = self.env.tf.shape(self)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 137, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 160, in shape_internal
    input_shape = input_tensor.get_shape()
  File "/local/dev/imperative/imperative/__amalgam__.py", line 142, in get_shape
    shape_tensor = self.env.tf.shape(self)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 137, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 160, in shape_internal
    input_shape = input_tensor.get_shape()
  File "/local/dev/imperative/imperative/__amalgam__.py", line 142, in get_shape
    shape_tensor = self.env.tf.shape(self)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 137, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 155, in shape_internal
    with ops.name_scope(name, "Shape", [input]) as name:
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4148, in name_scope
    g = _get_graph_from_inputs(values)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3916, in _get_graph_from_inputs
    if isinstance(op_input, (Operation, Tensor, SparseTensor, IndexedSlices)):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

This is only the very beginning and end of a very long, repetitive error.  Some kind of recursion.

**Comment by yaroslavvb** [comment]
Thanks for the issue (it seems my notifications were not setup). I've indeed not tried testing with Python3, it seems useful to have it run on both so I'll make it work
